apiVersion: apps/v1
kind: Deployment
metadata:
  name: backapp
  labels:
    homework: frontapp
    training: block4
spec:
  replicas: {{ .Values.backapp.replicaCount }}
  selector: 
    matchLabels: 
      homework: backapp
      training: block4
  template:
    metadata: 
      labels:
        homework: backapp
        training: block4
    spec:
      containers:
      - name: backapp
        image: quay.io/drsylent/cubix/block3/homework-backapp:springboot3
        env:
        - name: APP_DEFAULT_MESSAGE
          value: "{{ .Values.backapp.AppDefaultMessage }}"
        - name: JAVA_OPTS
          value: ""
